-- Produtos + RLS + bucket storage + seed inicial

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

create type public.product_status as enum ('active', 'inactive');

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  tags text[] default '{}',
  best_seller boolean not null default false,
  status public.product_status not null default 'active',
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_status_idx on public.products (status);
create index if not exists products_best_seller_idx on public.products (best_seller);

alter table public.products enable row level security;

drop policy if exists "products_select_active" on public.products;
create policy "products_select_active"
  on public.products
  for select
  using (status = 'active');

drop policy if exists "products_admin_all" on public.products;
create policy "products_admin_all"
  on public.products
  for all
  using (public.is_admin())
  with check (public.is_admin());

-- Impede usuário de alterar próprio role via update de perfil
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (
    auth.uid() = id
    and role = (select p.role from public.profiles p where p.id = auth.uid())
  );

-- Bucket público para imagens
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'products',
  'products',
  true,
  5242880,
  array['image/jpeg', 'image/jpg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = true,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "products_storage_public_read" on storage.objects;
create policy "products_storage_public_read"
  on storage.objects
  for select
  using (bucket_id = 'products');

drop policy if exists "products_storage_admin_insert" on storage.objects;
create policy "products_storage_admin_insert"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'products' and public.is_admin());

drop policy if exists "products_storage_admin_update" on storage.objects;
create policy "products_storage_admin_update"
  on storage.objects
  for update
  to authenticated
  using (bucket_id = 'products' and public.is_admin())
  with check (bucket_id = 'products' and public.is_admin());

drop policy if exists "products_storage_admin_delete" on storage.objects;
create policy "products_storage_admin_delete"
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'products' and public.is_admin());

-- Seed (mesmos dados de src/data/products.ts)
-- image_path: faça upload no bucket "products" com o mesmo caminho (ex: 1/Samambaia com Cesta.jpg)

insert into public.products (id, name, description, price, tags, best_seller, status, image_path)
values
  (1, 'Samambaia com Cesta', 'Beleza tropical e fácil de cuidar para seu ambiente!', 50.00, array['sombra parcial', 'interior'], true, 'active', '1/Samambaia com Cesta.jpg'),
  (2, 'Flecha-de-Macaco', 'Traz frescor e é perfeita para purificar o ar!', 20.00, array['sol pleno', 'interior'], true, 'active', '2/Flecha-de-Macaco.jpg'),
  (3, 'Roseira', 'As Rosas encantam e são perfeitas para presentear!', 10.00, array['sol pleno'], false, 'active', '3/Roseira.jpg'),
  (4, 'Clorofito', 'Traz leveza e é perfeita para purificar o ar!', 10.00, array['sombra parcial', 'interior'], false, 'active', '4/Clorofito.jpg'),
  (5, 'Cacto Mini-Palma', 'Traz estilo e é perfeito para decorar ambientes!', 15.00, array['sol pleno'], false, 'active', '5/Cacto Mini-Palma.jpg'),
  (6, 'Café de Salão', 'Traz elegância e renova a atmosfera da sua casa!', 15.00, array['sombra parcial', 'interior'], true, 'active', '6/Café de Salão.jpg'),
  (7, 'Mini Mandacaru', 'Traz simplicidade e é muito prático!', 15.00, array['sol pleno'], false, 'active', '7/Mini Mandacaru.jpg'),
  (8, 'Muda Clorofito Ocean', 'Traz frescor e é ideal para qualquer ambiente!', 5.00, array['sombra parcial', 'interior'], false, 'active', '8/Muda Clorofito Ocean.jpg'),
  (9, 'Orelha-de-Elefante', 'Traz um toque exótico e enche o espaço de vida e cor!', 20.00, array['sombra parcial'], false, 'active', '9/Orelha-de-Elefante.jpg'),
  (10, 'Muda Clúsia Variegata', 'Traz sofisticação e destaca-se com suas folhas únicas!', 10.00, array['sol pleno'], false, 'active', '10/Muda Clúsia Variegata.jpg'),
  (11, 'Muda Rosa do Deserto', 'Traz beleza e é perfeita para adicionar um toque tropical!', 15.00, array['sol pleno'], false, 'active', '11/Muda Rosa do Deserto.jpg'),
  (12, 'Mini Espada de São Jorge', 'Traz charme e é perfeita para decorar pequenos espaços!', 10.00, array['sombra parcial', 'interior'], false, 'active', '12/Mini Espada de São Jorge.jpg'),
  (13, 'Muda Cróton Canarinho', 'Traz cores vibrantes e ilumina qualquer ambiente com alegria!', 10.00, array['sol pleno'], false, 'active', '13/Muda Cróton Canarinho.jpg'),
  (14, 'Jiboia com Cesta', 'Traz um toque tropical e é ideal para pendurar e embelezar espaços!', 30.00, array['sombra parcial', 'interior'], true, 'active', '14/Jiboia com Cesta.jpg'),
  (15, 'Maranta Cascavel', 'Traz padrão único e é perfeita para adicionar frescor ao ambiente!', 20.00, array['sombra parcial', 'interior'], false, 'active', '15/Maranta Cascavel.jpg')
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  tags = excluded.tags,
  best_seller = excluded.best_seller,
  status = excluded.status,
  image_path = excluded.image_path,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  coalesce((select max(id) from public.products), 1)
);
